import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import bio from "../assets/bio.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Bienvenue sur mon Portfolio</h1>
      <h1>Biographie</h1>
      <Image src={bio} alt="Picture of the author" width={500} height={500} />
    </div>
  );
}
